; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "DAIL Insaller"
!define PRODUCT_VERSION "0019"
!define PRODUCT_PUBLISHER "Davoodinator"
!define PRODUCT_WEB_SITE "www.twitch.tv/davoodinator"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
;!insertmacro MUI_PAGE_LICENSE ".\DAILL.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup.exe"
InstallDir "$PROGRAMFILES\steam\steamapps\common\grim dawn\mods\"
ShowInstDetails show

Section "FULL DAIL" SEC01
  SetOutPath "$INSTDIR\database"
  SetOverwrite on
  File ".\S\database.arz"
SectionEnd

Section "ARACHNOPHOBIA" SEC02
  SetOutPath "$INSTDIR\database"
  SetOverwrite on
  File ".\A\database.arz"
SectionEnd

Section "DAIL WITHOUT GRIMM" SEC03
  SetOutPath "$INSTDIR\database"
  SetOverwrite on
  File ".\NG\database.arz"
SectionEnd

Section "ARACHNOPHOBIA WITHOUT GRIMM" SEC04
  SetOutPath "$INSTDIR\database"
  SetOverwrite on
  File ".\ANG\database.arz"
SectionEnd

Section "VANILLA" SEC05
SectionEnd

Section -Post
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} "ONLY CHOOSE ONE OF THESE NOT ALL OF THEM"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} "ONLY CHOOSE ONE OF THESE NOT ALL OF THEM"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC03} "ONLY CHOOSE ONE OF THESE NOT ALL OF THEM"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC04} "ONLY CHOOSE ONE OF THESE NOT ALL OF THEM"
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC05} "ONLY CHOOSE ONE OF THESE NOT ALL OF THEM"
!insertmacro MUI_FUNCTION_DESCRIPTION_END