call uups.bat "DAILmain - RIFT"
call uups.bat "DAILmain - Survival"
call uups.bat "DAILmain - A"
call uups.bat "DAILmain - A NG"
call uups.bat "DAILmain - A AB"
call uups.bat "DAILmain - ASX"
call uups.bat "DAILmain - AX"
call uups.bat "DAILmain - B"
call uups.bat "DAILmain - S"
call uups.bat "DAILmain - SX"
call uups.bat "DAILmain - X"