copy sct.dbr skills_classselectionbutton01.dbr /y
copy sct.dbr skills_classselectionbutton02.dbr /y
copy sct.dbr skills_classselectionbutton03.dbr /y
copy sct.dbr skills_classselectionbutton04.dbr /y
copy sct.dbr skills_classselectionbutton05.dbr /y
copy sct.dbr skills_classselectionbutton06.dbr /y
copy sct.dbr skills_classselectionbutton07.dbr /y
copy sct.dbr skills_classselectionbutton08.dbr /y
copy sct.dbr skills_classselectionbutton09.dbr /y
copy sct.dbr skills_classselectionbutton10.dbr /y
copy sct.dbr skills_classselectionbutton11.dbr /y
copy sct.dbr skills_classselectionbutton12.dbr /y
copy sct.dbr skills_classselectionbutton13.dbr /y
copy sct.dbr skills_classselectionbutton14.dbr /y
copy sct.dbr skills_classselectionbutton15.dbr /y
copy sct.dbr skills_classselectionbutton16.dbr /y
copy sct.dbr skills_classselectionbutton17.dbr /y
copy sct.dbr skills_classselectionbutton18.dbr /y
copy sct.dbr skills_classselectionbutton19.dbr /y
copy sct.dbr skills_classselectionbutton20.dbr /y
copy sct.dbr skills_classselectionbutton21.dbr /y
copy sct.dbr skills_classselectionbutton22.dbr /y
copy sct.dbr skills_classselectionbutton23.dbr /y
copy sct.dbr skills_classselectionbutton24.dbr /y
copy sct.dbr skills_classselectionbutton25.dbr /y
copy sct.dbr skills_classselectionbutton26.dbr /y
copy sct.dbr skills_classselectionbutton27.dbr /y
copy sct.dbr skills_classselectionbutton28.dbr /y
copy sct.dbr skills_classselectionbutton29.dbr /y
copy sct.dbr skills_classselectionbutton30.dbr /y
copy sct.dbr skills_classselectionbutton31.dbr /y
copy sct.dbr skills_classselectionbutton32.dbr /y
copy sct.dbr skills_classselectionbutton33.dbr /y
copy sct.dbr skills_classselectionbutton34.dbr /y
copy sct.dbr skills_classselectionbutton35.dbr /y
copy sct.dbr skills_classselectionbutton36.dbr /y
copy sct.dbr skills_classselectionbutton37.dbr /y
copy sct.dbr skills_classselectionbutton38.dbr /y
copy sct.dbr skills_classselectionbutton39.dbr /y
copy sct.dbr skills_classselectionbutton40.dbr /y
copy sct.dbr skills_classselectionbutton41.dbr /y
copy sct.dbr skills_classselectionbutton42.dbr /y
copy sct.dbr skills_classselectionbutton43.dbr /y
copy sct.dbr skills_classselectionbutton44.dbr /y
copy sct.dbr skills_classselectionbutton45.dbr /y
copy sct.dbr skills_classselectionbutton46.dbr /y
copy sct.dbr skills_classselectionbutton47.dbr /y
copy sct.dbr skills_classselectionbutton48.dbr /y
copy sct.dbr skills_classselectionbutton49.dbr /y
copy sct.dbr skills_classselectionbutton50.dbr /y
copy sct.dbr skills_classselectionbutton51.dbr /y
copy sct.dbr skills_classselectionbutton52.dbr /y
copy sct.dbr skills_classselectionbutton53.dbr /y
copy sct.dbr skills_classselectionbutton54.dbr /y
copy sct.dbr skills_classselectionbutton55.dbr /y
copy sct.dbr skills_classselectionbutton56.dbr /y
copy sct.dbr skills_classselectionbutton57.dbr /y
copy sct.dbr skills_classselectionbutton58.dbr /y
copy sct.dbr skills_classselectionbutton59.dbr /y
copy sct.dbr skills_classselectionbutton60.dbr /y
copy sct.dbr skills_classselectionbutton61.dbr /y
copy sct.dbr skills_classselectionbutton62.dbr /y
copy sct.dbr skills_classselectionbutton63.dbr /y
copy sct.dbr skills_classselectionbutton64.dbr /y
copy sct.dbr skills_classselectionbutton65.dbr /y
copy sct.dbr skills_classselectionbutton66.dbr /y
copy sct.dbr skills_classselectionbutton67.dbr /y
copy sct.dbr skills_classselectionbutton68.dbr /y
copy sct.dbr skills_classselectionbutton69.dbr /y
copy sct.dbr skills_classselectionbutton70.dbr /y
copy sct.dbr skills_classselectionbutton71.dbr /y
copy sct.dbr skills_classselectionbutton72.dbr /y
copy sct.dbr skills_classselectionbutton73.dbr /y
copy sct.dbr skills_classselectionbutton74.dbr /y
copy sct.dbr skills_classselectionbutton75.dbr /y
copy sct.dbr skills_classselectionbutton76.dbr /y
copy sct.dbr skills_classselectionbutton77.dbr /y
copy sct.dbr skills_classselectionbutton78.dbr /y
copy sct.dbr skills_classselectionbutton79.dbr /y
copy sct.dbr skills_classselectionbutton80.dbr /y
copy sct.dbr skills_classselectionbutton81.dbr /y
copy sct.dbr skills_classselectionbutton82.dbr /y
copy sct.dbr skills_classselectionbutton83.dbr /y
copy sct.dbr skills_classselectionbutton84.dbr /y
copy sct.dbr skills_classselectionbutton85.dbr /y
copy sct.dbr skills_classselectionbutton86.dbr /y
copy sct.dbr skills_classselectionbutton87.dbr /y
copy sct.dbr skills_classselectionbutton88.dbr /y
copy sct.dbr skills_classselectionbutton89.dbr /y
copy sct.dbr skills_classselectionbutton90.dbr /y
copy sct.dbr skills_classselectionbutton91.dbr /y
copy sct.dbr skills_classselectionbutton92.dbr /y
copy sct.dbr skills_classselectionbutton93.dbr /y
copy sct.dbr skills_classselectionbutton94.dbr /y
copy sct.dbr skills_classselectionbutton95.dbr /y
copy sct.dbr skills_classselectionbutton96.dbr /y
copy sct.dbr skills_classselectionbutton97.dbr /y
copy sct.dbr skills_classselectionbutton98.dbr /y
copy sct.dbr skills_classselectionbutton99.dbr /y
copy sst.dbr skills_classselectiontext01.dbr /y
copy sst.dbr skills_classselectiontext02.dbr /y
copy sst.dbr skills_classselectiontext03.dbr /y
copy sst.dbr skills_classselectiontext04.dbr /y
copy sst.dbr skills_classselectiontext05.dbr /y
copy sst.dbr skills_classselectiontext06.dbr /y
copy sst.dbr skills_classselectiontext07.dbr /y
copy sst.dbr skills_classselectiontext08.dbr /y
copy sst.dbr skills_classselectiontext09.dbr /y
copy sst.dbr skills_classselectiontext10.dbr /y
copy sst.dbr skills_classselectiontext11.dbr /y
copy sst.dbr skills_classselectiontext12.dbr /y
copy sst.dbr skills_classselectiontext13.dbr /y
copy sst.dbr skills_classselectiontext14.dbr /y
copy sst.dbr skills_classselectiontext15.dbr /y
copy sst.dbr skills_classselectiontext16.dbr /y
copy sst.dbr skills_classselectiontext17.dbr /y
copy sst.dbr skills_classselectiontext18.dbr /y
copy sst.dbr skills_classselectiontext19.dbr /y
copy sst.dbr skills_classselectiontext20.dbr /y
copy sst.dbr skills_classselectiontext21.dbr /y
copy sst.dbr skills_classselectiontext22.dbr /y
copy sst.dbr skills_classselectiontext23.dbr /y
copy sst.dbr skills_classselectiontext24.dbr /y
copy sst.dbr skills_classselectiontext25.dbr /y
copy sst.dbr skills_classselectiontext26.dbr /y
copy sst.dbr skills_classselectiontext27.dbr /y
copy sst.dbr skills_classselectiontext28.dbr /y
copy sst.dbr skills_classselectiontext29.dbr /y
copy sst.dbr skills_classselectiontext30.dbr /y
copy sst.dbr skills_classselectiontext31.dbr /y
copy sst.dbr skills_classselectiontext32.dbr /y
copy sst.dbr skills_classselectiontext33.dbr /y
copy sst.dbr skills_classselectiontext34.dbr /y
copy sst.dbr skills_classselectiontext35.dbr /y
copy sst.dbr skills_classselectiontext36.dbr /y
copy sst.dbr skills_classselectiontext37.dbr /y
copy sst.dbr skills_classselectiontext38.dbr /y
copy sst.dbr skills_classselectiontext39.dbr /y
copy sst.dbr skills_classselectiontext40.dbr /y
copy sst.dbr skills_classselectiontext41.dbr /y
copy sst.dbr skills_classselectiontext42.dbr /y
copy sst.dbr skills_classselectiontext43.dbr /y
copy sst.dbr skills_classselectiontext44.dbr /y
copy sst.dbr skills_classselectiontext45.dbr /y
copy sst.dbr skills_classselectiontext46.dbr /y
copy sst.dbr skills_classselectiontext47.dbr /y
copy sst.dbr skills_classselectiontext48.dbr /y
copy sst.dbr skills_classselectiontext49.dbr /y
copy sst.dbr skills_classselectiontext50.dbr /y
copy sst.dbr skills_classselectiontext51.dbr /y
copy sst.dbr skills_classselectiontext52.dbr /y
copy sst.dbr skills_classselectiontext53.dbr /y
copy sst.dbr skills_classselectiontext54.dbr /y
copy sst.dbr skills_classselectiontext55.dbr /y
copy sst.dbr skills_classselectiontext56.dbr /y
copy sst.dbr skills_classselectiontext57.dbr /y
copy sst.dbr skills_classselectiontext58.dbr /y
copy sst.dbr skills_classselectiontext59.dbr /y
copy sst.dbr skills_classselectiontext60.dbr /y
copy sst.dbr skills_classselectiontext61.dbr /y
copy sst.dbr skills_classselectiontext62.dbr /y
copy sst.dbr skills_classselectiontext63.dbr /y
copy sst.dbr skills_classselectiontext64.dbr /y
copy sst.dbr skills_classselectiontext65.dbr /y
copy sst.dbr skills_classselectiontext66.dbr /y
copy sst.dbr skills_classselectiontext67.dbr /y
copy sst.dbr skills_classselectiontext68.dbr /y
copy sst.dbr skills_classselectiontext69.dbr /y
copy sst.dbr skills_classselectiontext70.dbr /y
copy sst.dbr skills_classselectiontext71.dbr /y
copy sst.dbr skills_classselectiontext72.dbr /y
copy sst.dbr skills_classselectiontext73.dbr /y
copy sst.dbr skills_classselectiontext74.dbr /y
copy sst.dbr skills_classselectiontext75.dbr /y
copy sst.dbr skills_classselectiontext76.dbr /y
copy sst.dbr skills_classselectiontext77.dbr /y
copy sst.dbr skills_classselectiontext78.dbr /y
copy sst.dbr skills_classselectiontext79.dbr /y
copy sst.dbr skills_classselectiontext80.dbr /y
copy sst.dbr skills_classselectiontext81.dbr /y
copy sst.dbr skills_classselectiontext82.dbr /y
copy sst.dbr skills_classselectiontext83.dbr /y
copy sst.dbr skills_classselectiontext84.dbr /y
copy sst.dbr skills_classselectiontext85.dbr /y
copy sst.dbr skills_classselectiontext86.dbr /y
copy sst.dbr skills_classselectiontext87.dbr /y
copy sst.dbr skills_classselectiontext88.dbr /y
copy sst.dbr skills_classselectiontext89.dbr /y
copy sst.dbr skills_classselectiontext90.dbr /y
copy sst.dbr skills_classselectiontext91.dbr /y
copy sst.dbr skills_classselectiontext92.dbr /y
copy sst.dbr skills_classselectiontext93.dbr /y
copy sst.dbr skills_classselectiontext94.dbr /y
copy sst.dbr skills_classselectiontext95.dbr /y
copy sst.dbr skills_classselectiontext96.dbr /y
copy sst.dbr skills_classselectiontext97.dbr /y
copy sst.dbr skills_classselectiontext98.dbr /y
copy sst.dbr skills_classselectiontext99.dbr /y
echo bitmapPositionX,-68, >>  skills_classselectionbutton01.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton02.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton03.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton04.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton05.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton06.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton07.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton08.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton09.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton10.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton11.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton12.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton13.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton14.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton15.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton16.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton17.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton18.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton19.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton20.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton21.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton22.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton23.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton24.dbr 
echo bitmapPositionX,-68, >>  skills_classselectionbutton25.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton26.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton27.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton28.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton29.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton30.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton31.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton32.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton33.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton34.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton35.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton36.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton37.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton38.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton39.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton40.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton41.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton42.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton43.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton44.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton45.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton46.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton47.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton48.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton49.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton50.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton51.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton52.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton53.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton54.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton55.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton56.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton57.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton58.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton59.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton60.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton61.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton62.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton63.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton64.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton65.dbr 
echo bitmapPositionX,750, >>  skills_classselectionbutton66.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton67.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton68.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton69.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton70.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton71.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton72.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton73.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton74.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton75.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton76.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton77.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton78.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton79.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton80.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton81.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton82.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton83.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton84.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton85.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton86.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton87.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton88.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton89.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton90.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton91.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton92.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton93.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton94.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton95.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton96.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton97.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton98.dbr 
echo bitmapPositionX,1025, >>  skills_classselectionbutton99.dbr 
echo bitmapPositionY,SST Y, >>  skills_classselectionbutton01.dbr 
echo bitmapPositionY,0, >>  skills_classselectionbutton01.dbr 
echo bitmapPositionY,23, >>  skills_classselectionbutton02.dbr 
echo bitmapPositionY,46, >>  skills_classselectionbutton03.dbr 
echo bitmapPositionY,69, >>  skills_classselectionbutton04.dbr 
echo bitmapPositionY,92, >>  skills_classselectionbutton05.dbr 
echo bitmapPositionY,115, >>  skills_classselectionbutton06.dbr 
echo bitmapPositionY,138, >>  skills_classselectionbutton07.dbr 
echo bitmapPositionY,161, >>  skills_classselectionbutton08.dbr 
echo bitmapPositionY,184, >>  skills_classselectionbutton09.dbr 
echo bitmapPositionY,207, >>  skills_classselectionbutton10.dbr 
echo bitmapPositionY,230, >>  skills_classselectionbutton11.dbr 
echo bitmapPositionY,253, >>  skills_classselectionbutton12.dbr 
echo bitmapPositionY,276, >>  skills_classselectionbutton13.dbr 
echo bitmapPositionY,299, >>  skills_classselectionbutton14.dbr 
echo bitmapPositionY,322, >>  skills_classselectionbutton15.dbr 
echo bitmapPositionY,345, >>  skills_classselectionbutton16.dbr 
echo bitmapPositionY,368, >>  skills_classselectionbutton17.dbr 
echo bitmapPositionY,391, >>  skills_classselectionbutton18.dbr 
echo bitmapPositionY,414, >>  skills_classselectionbutton19.dbr 
echo bitmapPositionY,437, >>  skills_classselectionbutton20.dbr 
echo bitmapPositionY,460, >>  skills_classselectionbutton21.dbr 
echo bitmapPositionY,483, >>  skills_classselectionbutton22.dbr 
echo bitmapPositionY,506, >>  skills_classselectionbutton23.dbr 
echo bitmapPositionY,529, >>  skills_classselectionbutton24.dbr 
echo bitmapPositionY,552, >>  skills_classselectionbutton25.dbr 
echo bitmapPositionY,0, >>  skills_classselectionbutton26.dbr 
echo bitmapPositionY,23, >>  skills_classselectionbutton27.dbr 
echo bitmapPositionY,46, >>  skills_classselectionbutton28.dbr 
echo bitmapPositionY,69, >>  skills_classselectionbutton29.dbr 
echo bitmapPositionY,92, >>  skills_classselectionbutton30.dbr 
echo bitmapPositionY,115, >>  skills_classselectionbutton31.dbr 
echo bitmapPositionY,138, >>  skills_classselectionbutton32.dbr 
echo bitmapPositionY,161, >>  skills_classselectionbutton33.dbr 
echo bitmapPositionY,184, >>  skills_classselectionbutton34.dbr 
echo bitmapPositionY,207, >>  skills_classselectionbutton35.dbr 
echo bitmapPositionY,230, >>  skills_classselectionbutton36.dbr 
echo bitmapPositionY,253, >>  skills_classselectionbutton37.dbr 
echo bitmapPositionY,276, >>  skills_classselectionbutton38.dbr 
echo bitmapPositionY,299, >>  skills_classselectionbutton39.dbr 
echo bitmapPositionY,322, >>  skills_classselectionbutton40.dbr 
echo bitmapPositionY,345, >>  skills_classselectionbutton41.dbr 
echo bitmapPositionY,368, >>  skills_classselectionbutton42.dbr 
echo bitmapPositionY,391, >>  skills_classselectionbutton43.dbr 
echo bitmapPositionY,414, >>  skills_classselectionbutton44.dbr 
echo bitmapPositionY,437, >>  skills_classselectionbutton45.dbr 
echo bitmapPositionY,460, >>  skills_classselectionbutton46.dbr 
echo bitmapPositionY,483, >>  skills_classselectionbutton47.dbr 
echo bitmapPositionY,506, >>  skills_classselectionbutton48.dbr 
echo bitmapPositionY,529, >>  skills_classselectionbutton49.dbr 
echo bitmapPositionY,552, >>  skills_classselectionbutton50.dbr 
echo bitmapPositionY,575, >>  skills_classselectionbutton51.dbr 
echo bitmapPositionY,598, >>  skills_classselectionbutton52.dbr 
echo bitmapPositionY,621, >>  skills_classselectionbutton53.dbr 
echo bitmapPositionY,644, >>  skills_classselectionbutton54.dbr 
echo bitmapPositionY,667, >>  skills_classselectionbutton55.dbr 
echo bitmapPositionY,690, >>  skills_classselectionbutton56.dbr 
echo bitmapPositionY,713, >>  skills_classselectionbutton57.dbr 
echo bitmapPositionY,736, >>  skills_classselectionbutton58.dbr 
echo bitmapPositionY,759, >>  skills_classselectionbutton59.dbr 
echo bitmapPositionY,782, >>  skills_classselectionbutton60.dbr 
echo bitmapPositionY,805, >>  skills_classselectionbutton61.dbr 
echo bitmapPositionY,828, >>  skills_classselectionbutton62.dbr 
echo bitmapPositionY,851, >>  skills_classselectionbutton63.dbr 
echo bitmapPositionY,874, >>  skills_classselectionbutton64.dbr 
echo bitmapPositionY,897, >>  skills_classselectionbutton65.dbr 
echo bitmapPositionY,920, >>  skills_classselectionbutton66.dbr 
echo bitmapPositionY,0, >>  skills_classselectionbutton67.dbr 
echo bitmapPositionY,23, >>  skills_classselectionbutton68.dbr 
echo bitmapPositionY,46, >>  skills_classselectionbutton69.dbr 
echo bitmapPositionY,69, >>  skills_classselectionbutton70.dbr 
echo bitmapPositionY,92, >>  skills_classselectionbutton71.dbr 
echo bitmapPositionY,115, >>  skills_classselectionbutton72.dbr 
echo bitmapPositionY,138, >>  skills_classselectionbutton73.dbr 
echo bitmapPositionY,161, >>  skills_classselectionbutton74.dbr 
echo bitmapPositionY,184, >>  skills_classselectionbutton75.dbr 
echo bitmapPositionY,207, >>  skills_classselectionbutton76.dbr 
echo bitmapPositionY,230, >>  skills_classselectionbutton77.dbr 
echo bitmapPositionY,253, >>  skills_classselectionbutton78.dbr 
echo bitmapPositionY,276, >>  skills_classselectionbutton79.dbr 
echo bitmapPositionY,299, >>  skills_classselectionbutton80.dbr 
echo bitmapPositionY,322, >>  skills_classselectionbutton81.dbr 
echo bitmapPositionY,345, >>  skills_classselectionbutton82.dbr 
echo bitmapPositionY,368, >>  skills_classselectionbutton83.dbr 
echo bitmapPositionY,391, >>  skills_classselectionbutton84.dbr 
echo bitmapPositionY,414, >>  skills_classselectionbutton85.dbr 
echo bitmapPositionY,437, >>  skills_classselectionbutton86.dbr 
echo bitmapPositionY,460, >>  skills_classselectionbutton87.dbr 
echo bitmapPositionY,483, >>  skills_classselectionbutton88.dbr 
echo bitmapPositionY,506, >>  skills_classselectionbutton89.dbr 
echo bitmapPositionY,529, >>  skills_classselectionbutton90.dbr 
echo bitmapPositionY,552, >>  skills_classselectionbutton91.dbr 
echo bitmapPositionY,575, >>  skills_classselectionbutton92.dbr 
echo bitmapPositionY,598, >>  skills_classselectionbutton93.dbr 
echo bitmapPositionY,621, >>  skills_classselectionbutton94.dbr 
echo bitmapPositionY,644, >>  skills_classselectionbutton95.dbr 
echo bitmapPositionY,667, >>  skills_classselectionbutton96.dbr 
echo bitmapPositionY,690, >>  skills_classselectionbutton97.dbr 
echo bitmapPositionY,713, >>  skills_classselectionbutton98.dbr 
echo textBoxX,-68, >>   skills_classselectiontext01.dbr
echo textBoxX,-68, >>   skills_classselectiontext02.dbr
echo textBoxX,-68, >>   skills_classselectiontext03.dbr
echo textBoxX,-68, >>   skills_classselectiontext04.dbr
echo textBoxX,-68, >>   skills_classselectiontext05.dbr
echo textBoxX,-68, >>   skills_classselectiontext06.dbr
echo textBoxX,-68, >>   skills_classselectiontext07.dbr
echo textBoxX,-68, >>   skills_classselectiontext08.dbr
echo textBoxX,-68, >>   skills_classselectiontext09.dbr
echo textBoxX,-68, >>   skills_classselectiontext10.dbr
echo textBoxX,-68, >>   skills_classselectiontext11.dbr
echo textBoxX,-68, >>   skills_classselectiontext12.dbr
echo textBoxX,-68, >>   skills_classselectiontext13.dbr
echo textBoxX,-68, >>   skills_classselectiontext14.dbr
echo textBoxX,-68, >>   skills_classselectiontext15.dbr
echo textBoxX,-68, >>   skills_classselectiontext16.dbr
echo textBoxX,-68, >>   skills_classselectiontext17.dbr
echo textBoxX,-68, >>   skills_classselectiontext18.dbr
echo textBoxX,-68, >>   skills_classselectiontext19.dbr
echo textBoxX,-68, >>   skills_classselectiontext20.dbr
echo textBoxX,-68, >>   skills_classselectiontext21.dbr
echo textBoxX,-68, >>   skills_classselectiontext22.dbr
echo textBoxX,-68, >>   skills_classselectiontext23.dbr
echo textBoxX,-68, >>   skills_classselectiontext24.dbr
echo textBoxX,-68, >>   skills_classselectiontext25.dbr
echo textBoxX,750, >>   skills_classselectiontext26.dbr
echo textBoxX,750, >>   skills_classselectiontext27.dbr
echo textBoxX,750, >>   skills_classselectiontext28.dbr
echo textBoxX,750, >>   skills_classselectiontext29.dbr
echo textBoxX,750, >>   skills_classselectiontext30.dbr
echo textBoxX,750, >>   skills_classselectiontext31.dbr
echo textBoxX,750, >>   skills_classselectiontext32.dbr
echo textBoxX,750, >>   skills_classselectiontext33.dbr
echo textBoxX,750, >>   skills_classselectiontext34.dbr
echo textBoxX,750, >>   skills_classselectiontext35.dbr
echo textBoxX,750, >>   skills_classselectiontext36.dbr
echo textBoxX,750, >>   skills_classselectiontext37.dbr
echo textBoxX,750, >>   skills_classselectiontext38.dbr
echo textBoxX,750, >>   skills_classselectiontext39.dbr
echo textBoxX,750, >>   skills_classselectiontext40.dbr
echo textBoxX,750, >>   skills_classselectiontext41.dbr
echo textBoxX,750, >>   skills_classselectiontext42.dbr
echo textBoxX,750, >>   skills_classselectiontext43.dbr
echo textBoxX,750, >>   skills_classselectiontext44.dbr
echo textBoxX,750, >>   skills_classselectiontext45.dbr
echo textBoxX,750, >>   skills_classselectiontext46.dbr
echo textBoxX,750, >>   skills_classselectiontext47.dbr
echo textBoxX,750, >>   skills_classselectiontext48.dbr
echo textBoxX,750, >>   skills_classselectiontext49.dbr
echo textBoxX,750, >>   skills_classselectiontext50.dbr
echo textBoxX,750, >>   skills_classselectiontext51.dbr
echo textBoxX,750, >>   skills_classselectiontext52.dbr
echo textBoxX,750, >>   skills_classselectiontext53.dbr
echo textBoxX,750, >>   skills_classselectiontext54.dbr
echo textBoxX,750, >>   skills_classselectiontext55.dbr
echo textBoxX,750, >>   skills_classselectiontext56.dbr
echo textBoxX,750, >>   skills_classselectiontext57.dbr
echo textBoxX,750, >>   skills_classselectiontext58.dbr
echo textBoxX,750, >>   skills_classselectiontext59.dbr
echo textBoxX,750, >>   skills_classselectiontext60.dbr
echo textBoxX,750, >>   skills_classselectiontext61.dbr
echo textBoxX,750, >>   skills_classselectiontext62.dbr
echo textBoxX,750, >>   skills_classselectiontext63.dbr
echo textBoxX,750, >>   skills_classselectiontext64.dbr
echo textBoxX,750, >>   skills_classselectiontext65.dbr
echo textBoxX,750, >>   skills_classselectiontext66.dbr
echo textBoxX,1025, >>   skills_classselectiontext67.dbr
echo textBoxX,1025, >>   skills_classselectiontext68.dbr
echo textBoxX,1025, >>   skills_classselectiontext69.dbr
echo textBoxX,1025, >>   skills_classselectiontext70.dbr
echo textBoxX,1025, >>   skills_classselectiontext71.dbr
echo textBoxX,1025, >>   skills_classselectiontext72.dbr
echo textBoxX,1025, >>   skills_classselectiontext73.dbr
echo textBoxX,1025, >>   skills_classselectiontext74.dbr
echo textBoxX,1025, >>   skills_classselectiontext75.dbr
echo textBoxX,1025, >>   skills_classselectiontext76.dbr
echo textBoxX,1025, >>   skills_classselectiontext77.dbr
echo textBoxX,1025, >>   skills_classselectiontext78.dbr
echo textBoxX,1025, >>   skills_classselectiontext79.dbr
echo textBoxX,1025, >>   skills_classselectiontext80.dbr
echo textBoxX,1025, >>   skills_classselectiontext81.dbr
echo textBoxX,1025, >>   skills_classselectiontext82.dbr
echo textBoxX,1025, >>   skills_classselectiontext83.dbr
echo textBoxX,1025, >>   skills_classselectiontext84.dbr
echo textBoxX,1025, >>   skills_classselectiontext85.dbr
echo textBoxX,1025, >>   skills_classselectiontext86.dbr
echo textBoxX,1025, >>   skills_classselectiontext87.dbr
echo textBoxX,1025, >>   skills_classselectiontext88.dbr
echo textBoxX,1025, >>   skills_classselectiontext89.dbr
echo textBoxX,1025, >>   skills_classselectiontext90.dbr
echo textBoxX,1025, >>   skills_classselectiontext91.dbr
echo textBoxX,1025, >>   skills_classselectiontext92.dbr
echo textBoxX,1025, >>   skills_classselectiontext93.dbr
echo textBoxX,1025, >>   skills_classselectiontext94.dbr
echo textBoxX,1025, >>   skills_classselectiontext95.dbr
echo textBoxX,1025, >>   skills_classselectiontext96.dbr
echo textBoxX,1025, >>   skills_classselectiontext97.dbr
echo textBoxX,1025, >>   skills_classselectiontext98.dbr
echo textBoxX,1025, >>   skills_classselectiontext99.dbr
echo textBoxY,0, >>   skills_classselectiontext01.dbr
echo textBoxY,23, >>   skills_classselectiontext02.dbr
echo textBoxY,46, >>   skills_classselectiontext03.dbr
echo textBoxY,69, >>   skills_classselectiontext04.dbr
echo textBoxY,92, >>   skills_classselectiontext05.dbr
echo textBoxY,115, >>   skills_classselectiontext06.dbr
echo textBoxY,138, >>   skills_classselectiontext07.dbr
echo textBoxY,161, >>   skills_classselectiontext08.dbr
echo textBoxY,184, >>   skills_classselectiontext09.dbr
echo textBoxY,207, >>   skills_classselectiontext10.dbr
echo textBoxY,230, >>   skills_classselectiontext11.dbr
echo textBoxY,253, >>   skills_classselectiontext12.dbr
echo textBoxY,276, >>   skills_classselectiontext13.dbr
echo textBoxY,299, >>   skills_classselectiontext14.dbr
echo textBoxY,322, >>   skills_classselectiontext15.dbr
echo textBoxY,345, >>   skills_classselectiontext16.dbr
echo textBoxY,368, >>   skills_classselectiontext17.dbr
echo textBoxY,391, >>   skills_classselectiontext18.dbr
echo textBoxY,414, >>   skills_classselectiontext19.dbr
echo textBoxY,437, >>   skills_classselectiontext20.dbr
echo textBoxY,460, >>   skills_classselectiontext21.dbr
echo textBoxY,483, >>   skills_classselectiontext22.dbr
echo textBoxY,506, >>   skills_classselectiontext23.dbr
echo textBoxY,529, >>   skills_classselectiontext24.dbr
echo textBoxY,552, >>   skills_classselectiontext25.dbr
echo textBoxY,0, >>   skills_classselectiontext26.dbr
echo textBoxY,23, >>   skills_classselectiontext27.dbr
echo textBoxY,46, >>   skills_classselectiontext28.dbr
echo textBoxY,69, >>   skills_classselectiontext29.dbr
echo textBoxY,92, >>   skills_classselectiontext30.dbr
echo textBoxY,115, >>   skills_classselectiontext31.dbr
echo textBoxY,138, >>   skills_classselectiontext32.dbr
echo textBoxY,161, >>   skills_classselectiontext33.dbr
echo textBoxY,184, >>   skills_classselectiontext34.dbr
echo textBoxY,207, >>   skills_classselectiontext35.dbr
echo textBoxY,230, >>   skills_classselectiontext36.dbr
echo textBoxY,253, >>   skills_classselectiontext37.dbr
echo textBoxY,276, >>   skills_classselectiontext38.dbr
echo textBoxY,299, >>   skills_classselectiontext39.dbr
echo textBoxY,322, >>   skills_classselectiontext40.dbr
echo textBoxY,345, >>   skills_classselectiontext41.dbr
echo textBoxY,368, >>   skills_classselectiontext42.dbr
echo textBoxY,391, >>   skills_classselectiontext43.dbr
echo textBoxY,414, >>   skills_classselectiontext44.dbr
echo textBoxY,437, >>   skills_classselectiontext45.dbr
echo textBoxY,460, >>   skills_classselectiontext46.dbr
echo textBoxY,483, >>   skills_classselectiontext47.dbr
echo textBoxY,506, >>   skills_classselectiontext48.dbr
echo textBoxY,529, >>   skills_classselectiontext49.dbr
echo textBoxY,552, >>   skills_classselectiontext50.dbr
echo textBoxY,575, >>   skills_classselectiontext51.dbr
echo textBoxY,598, >>   skills_classselectiontext52.dbr
echo textBoxY,621, >>   skills_classselectiontext53.dbr
echo textBoxY,644, >>   skills_classselectiontext54.dbr
echo textBoxY,667, >>   skills_classselectiontext55.dbr
echo textBoxY,690, >>   skills_classselectiontext56.dbr
echo textBoxY,713, >>   skills_classselectiontext57.dbr
echo textBoxY,736, >>   skills_classselectiontext58.dbr
echo textBoxY,759, >>   skills_classselectiontext59.dbr
echo textBoxY,782, >>   skills_classselectiontext60.dbr
echo textBoxY,805, >>   skills_classselectiontext61.dbr
echo textBoxY,828, >>   skills_classselectiontext62.dbr
echo textBoxY,851, >>   skills_classselectiontext63.dbr
echo textBoxY,874, >>   skills_classselectiontext64.dbr
echo textBoxY,897, >>   skills_classselectiontext65.dbr
echo textBoxY,920, >>   skills_classselectiontext66.dbr
echo textBoxY,0, >>   skills_classselectiontext67.dbr
echo textBoxY,23, >>   skills_classselectiontext68.dbr
echo textBoxY,46, >>   skills_classselectiontext69.dbr
echo textBoxY,69, >>   skills_classselectiontext70.dbr
echo textBoxY,92, >>   skills_classselectiontext71.dbr
echo textBoxY,115, >>   skills_classselectiontext72.dbr
echo textBoxY,138, >>   skills_classselectiontext73.dbr
echo textBoxY,161, >>   skills_classselectiontext74.dbr
echo textBoxY,184, >>   skills_classselectiontext75.dbr
echo textBoxY,207, >>   skills_classselectiontext76.dbr
echo textBoxY,230, >>   skills_classselectiontext77.dbr
echo textBoxY,253, >>   skills_classselectiontext78.dbr
echo textBoxY,276, >>   skills_classselectiontext79.dbr
echo textBoxY,299, >>   skills_classselectiontext80.dbr
echo textBoxY,322, >>   skills_classselectiontext81.dbr
echo textBoxY,345, >>   skills_classselectiontext82.dbr
echo textBoxY,368, >>   skills_classselectiontext83.dbr
echo textBoxY,391, >>   skills_classselectiontext84.dbr
echo textBoxY,414, >>   skills_classselectiontext85.dbr
echo textBoxY,437, >>   skills_classselectiontext86.dbr
echo textBoxY,460, >>   skills_classselectiontext87.dbr
echo textBoxY,483, >>   skills_classselectiontext88.dbr
echo textBoxY,506, >>   skills_classselectiontext89.dbr
echo textBoxY,529, >>   skills_classselectiontext90.dbr
echo textBoxY,552, >>   skills_classselectiontext91.dbr
echo textBoxY,575, >>   skills_classselectiontext92.dbr
echo textBoxY,598, >>   skills_classselectiontext93.dbr
echo textBoxY,621, >>   skills_classselectiontext94.dbr
echo textBoxY,644, >>   skills_classselectiontext95.dbr
echo textBoxY,667, >>   skills_classselectiontext96.dbr
echo textBoxY,690, >>   skills_classselectiontext97.dbr
echo textBoxY,713, >>   skills_classselectiontext98.dbr
echo textBoxY,736, >>   skills_classselectiontext99.dbr
echo textTag,tagSkillClassName01, >>   skills_classselectiontext01.dbr
echo textTag,tagSkillClassName02, >>   skills_classselectiontext02.dbr
echo textTag,tagSkillClassName03, >>   skills_classselectiontext03.dbr
echo textTag,tagSkillClassName04, >>   skills_classselectiontext04.dbr
echo textTag,tagSkillClassName05, >>   skills_classselectiontext05.dbr
echo textTag,tagSkillClassName06, >>   skills_classselectiontext06.dbr
echo textTag,tagSkillClassName07, >>   skills_classselectiontext07.dbr
echo textTag,tagSkillClassName08, >>   skills_classselectiontext08.dbr
echo textTag,tagSkillClassName09, >>   skills_classselectiontext09.dbr
echo textTag,tagSkillClassName10, >>   skills_classselectiontext10.dbr
echo textTag,tagSkillClassName11, >>   skills_classselectiontext11.dbr
echo textTag,tagSkillClassName12, >>   skills_classselectiontext12.dbr
echo textTag,tagSkillClassName13, >>   skills_classselectiontext13.dbr
echo textTag,tagSkillClassName14, >>   skills_classselectiontext14.dbr
echo textTag,tagSkillClassName15, >>   skills_classselectiontext15.dbr
echo textTag,tagSkillClassName16, >>   skills_classselectiontext16.dbr
echo textTag,tagSkillClassName17, >>   skills_classselectiontext17.dbr
echo textTag,tagSkillClassName18, >>   skills_classselectiontext18.dbr
echo textTag,tagSkillClassName19, >>   skills_classselectiontext19.dbr
echo textTag,tagSkillClassName20, >>   skills_classselectiontext20.dbr
echo textTag,tagSkillClassName21, >>   skills_classselectiontext21.dbr
echo textTag,tagSkillClassName22, >>   skills_classselectiontext22.dbr
echo textTag,tagSkillClassName23, >>   skills_classselectiontext23.dbr
echo textTag,tagSkillClassName24, >>   skills_classselectiontext24.dbr
echo textTag,tagSkillClassName25, >>   skills_classselectiontext25.dbr
echo textTag,tagSkillClassName26, >>   skills_classselectiontext26.dbr
echo textTag,tagSkillClassName27, >>   skills_classselectiontext27.dbr
echo textTag,tagSkillClassName28, >>   skills_classselectiontext28.dbr
echo textTag,tagSkillClassName29, >>   skills_classselectiontext29.dbr
echo textTag,tagSkillClassName30, >>   skills_classselectiontext30.dbr
echo textTag,tagSkillClassName31, >>   skills_classselectiontext31.dbr
echo textTag,tagSkillClassName32, >>   skills_classselectiontext32.dbr
echo textTag,tagSkillClassName33, >>   skills_classselectiontext33.dbr
echo textTag,tagSkillClassName34, >>   skills_classselectiontext34.dbr
echo textTag,tagSkillClassName35, >>   skills_classselectiontext35.dbr
echo textTag,tagSkillClassName36, >>   skills_classselectiontext36.dbr
echo textTag,tagSkillClassName37, >>   skills_classselectiontext37.dbr
echo textTag,tagSkillClassName38, >>   skills_classselectiontext38.dbr
echo textTag,tagSkillClassName39, >>   skills_classselectiontext39.dbr
echo textTag,tagSkillClassName40, >>   skills_classselectiontext40.dbr
echo textTag,tagSkillClassName41, >>   skills_classselectiontext41.dbr
echo textTag,tagSkillClassName42, >>   skills_classselectiontext42.dbr
echo textTag,tagSkillClassName43, >>   skills_classselectiontext43.dbr
echo textTag,tagSkillClassName44, >>   skills_classselectiontext44.dbr
echo textTag,tagSkillClassName45, >>   skills_classselectiontext45.dbr
echo textTag,tagSkillClassName46, >>   skills_classselectiontext46.dbr
echo textTag,tagSkillClassName47, >>   skills_classselectiontext47.dbr
echo textTag,tagSkillClassName48, >>   skills_classselectiontext48.dbr
echo textTag,tagSkillClassName49, >>   skills_classselectiontext49.dbr
echo textTag,tagSkillClassName50, >>   skills_classselectiontext50.dbr
echo textTag,tagSkillClassName51, >>   skills_classselectiontext51.dbr
echo textTag,tagSkillClassName52, >>   skills_classselectiontext52.dbr
echo textTag,tagSkillClassName53, >>   skills_classselectiontext53.dbr
echo textTag,tagSkillClassName54, >>   skills_classselectiontext54.dbr
echo textTag,tagSkillClassName55, >>   skills_classselectiontext55.dbr
echo textTag,tagSkillClassName56, >>   skills_classselectiontext56.dbr
echo textTag,tagSkillClassName57, >>   skills_classselectiontext57.dbr
echo textTag,tagSkillClassName58, >>   skills_classselectiontext58.dbr
echo textTag,tagSkillClassName59, >>   skills_classselectiontext59.dbr
echo textTag,tagSkillClassName60, >>   skills_classselectiontext60.dbr
echo textTag,tagSkillClassName61, >>   skills_classselectiontext61.dbr
echo textTag,tagSkillClassName62, >>   skills_classselectiontext62.dbr
echo textTag,tagSkillClassName63, >>   skills_classselectiontext63.dbr
echo textTag,tagSkillClassName64, >>   skills_classselectiontext64.dbr
echo textTag,tagSkillClassName65, >>   skills_classselectiontext65.dbr
echo textTag,tagSkillClassName66, >>   skills_classselectiontext66.dbr
echo textTag,tagSkillClassName67, >>   skills_classselectiontext67.dbr
echo textTag,tagSkillClassName68, >>   skills_classselectiontext68.dbr
echo textTag,tagSkillClassName69, >>   skills_classselectiontext69.dbr
echo textTag,tagSkillClassName70, >>   skills_classselectiontext70.dbr
echo textTag,tagSkillClassName71, >>   skills_classselectiontext71.dbr
echo textTag,tagSkillClassName72, >>   skills_classselectiontext72.dbr
echo textTag,tagSkillClassName73, >>   skills_classselectiontext73.dbr
echo textTag,tagSkillClassName74, >>   skills_classselectiontext74.dbr
echo textTag,tagSkillClassName75, >>   skills_classselectiontext75.dbr
echo textTag,tagSkillClassName76, >>   skills_classselectiontext76.dbr
echo textTag,tagSkillClassName77, >>   skills_classselectiontext77.dbr
echo textTag,tagSkillClassName78, >>   skills_classselectiontext78.dbr
echo textTag,tagSkillClassName79, >>   skills_classselectiontext79.dbr
echo textTag,tagSkillClassName80, >>   skills_classselectiontext80.dbr
echo textTag,tagSkillClassName81, >>   skills_classselectiontext81.dbr
echo textTag,tagSkillClassName82, >>   skills_classselectiontext82.dbr
echo textTag,tagSkillClassName83, >>   skills_classselectiontext83.dbr
echo textTag,tagSkillClassName84, >>   skills_classselectiontext84.dbr
echo textTag,tagSkillClassName85, >>   skills_classselectiontext85.dbr
echo textTag,tagSkillClassName86, >>   skills_classselectiontext86.dbr
echo textTag,tagSkillClassName87, >>   skills_classselectiontext87.dbr
echo textTag,tagSkillClassName88, >>   skills_classselectiontext88.dbr
echo textTag,tagSkillClassName89, >>   skills_classselectiontext89.dbr
echo textTag,tagSkillClassName90, >>   skills_classselectiontext90.dbr
echo textTag,tagSkillClassName91, >>   skills_classselectiontext91.dbr
echo textTag,tagSkillClassName92, >>   skills_classselectiontext92.dbr
echo textTag,tagSkillClassName93, >>   skills_classselectiontext93.dbr
echo textTag,tagSkillClassName94, >>   skills_classselectiontext94.dbr
echo textTag,tagSkillClassName95, >>   skills_classselectiontext95.dbr
echo textTag,tagSkillClassName96, >>   skills_classselectiontext96.dbr
echo textTag,tagSkillClassName97, >>   skills_classselectiontext97.dbr
echo textTag,tagSkillClassName98, >>   skills_classselectiontext98.dbr
echo textTag,tagSkillClassName99, >>   skills_classselectiontext99.dbr
