rem setup templates for items for summoning
rem skillName,records/skills/itemskills/consumableskills/item_cratebox.dbr,
copy base_summon_item.dbr .\items\summon\dailskillsummon0001.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0002.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0003.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0004.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0005.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0006.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0007.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0008.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0009.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0010.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0011.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0012.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0013.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0014.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0015.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0016.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0017.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0018.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0019.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0020.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0021.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0022.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0023.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0024.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0025.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0026.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0027.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0028.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0029.dbr /y
copy base_summon_item.dbr .\items\summon\dailskillsummon0030.dbr /y
copy base_summon_item.dbr .\items\summon\dailfactionsummon0001.dbr /y
copy base_summon_item.dbr .\items\summon\dailfactionsummon0002.dbr /y
copy base_summon_item.dbr .\items\summon\dailfactionsummon0003.dbr /y

rem  add script call
rem  onDestroy,omega.complete.quest1,
echo onDestroy,dail.summon.item_cratebox, >> .\items\summon\cratebox.dbr
echo onDestroy,dail.summon.dailskillsummon0001, >> .\items\summon\dailskillsummon0001.dbr
echo onDestroy,dail.summon.dailskillsummon0002, >> .\items\summon\dailskillsummon0002.dbr
echo onDestroy,dail.summon.dailskillsummon0003, >> .\items\summon\dailskillsummon0003.dbr
echo onDestroy,dail.summon.dailskillsummon0004, >> .\items\summon\dailskillsummon0004.dbr
echo onDestroy,dail.summon.dailskillsummon0005, >> .\items\summon\dailskillsummon0005.dbr
echo onDestroy,dail.summon.dailskillsummon0006, >> .\items\summon\dailskillsummon0006.dbr
echo onDestroy,dail.summon.dailskillsummon0007, >> .\items\summon\dailskillsummon0007.dbr
echo onDestroy,dail.summon.dailskillsummon0008, >> .\items\summon\dailskillsummon0008.dbr
echo onDestroy,dail.summon.dailskillsummon0009, >> .\items\summon\dailskillsummon0009.dbr
echo onDestroy,dail.summon.dailskillsummon0010, >> .\items\summon\dailskillsummon0010.dbr
echo onDestroy,dail.summon.dailskillsummon0011, >> .\items\summon\dailskillsummon0011.dbr
echo onDestroy,dail.summon.dailskillsummon0012, >> .\items\summon\dailskillsummon0012.dbr
echo onDestroy,dail.summon.dailskillsummon0013, >> .\items\summon\dailskillsummon0013.dbr
echo onDestroy,dail.summon.dailskillsummon0014, >> .\items\summon\dailskillsummon0014.dbr
echo onDestroy,dail.summon.dailskillsummon0015, >> .\items\summon\dailskillsummon0015.dbr
echo onDestroy,dail.summon.dailskillsummon0016, >> .\items\summon\dailskillsummon0016.dbr
echo onDestroy,dail.summon.dailskillsummon0017, >> .\items\summon\dailskillsummon0017.dbr
echo onDestroy,dail.summon.dailskillsummon0018, >> .\items\summon\dailskillsummon0018.dbr
echo onDestroy,dail.summon.dailskillsummon0019, >> .\items\summon\dailskillsummon0019.dbr
echo onDestroy,dail.summon.dailskillsummon0020, >> .\items\summon\dailskillsummon0020.dbr
echo onDestroy,dail.summon.dailskillsummon0021, >> .\items\summon\dailskillsummon0021.dbr
echo onDestroy,dail.summon.dailskillsummon0022, >> .\items\summon\dailskillsummon0022.dbr
echo onDestroy,dail.summon.dailskillsummon0023, >> .\items\summon\dailskillsummon0023.dbr
echo onDestroy,dail.summon.dailskillsummon0024, >> .\items\summon\dailskillsummon0024.dbr
echo onDestroy,dail.summon.dailskillsummon0025, >> .\items\summon\dailskillsummon0025.dbr
echo onDestroy,dail.summon.dailskillsummon0026, >> .\items\summon\dailskillsummon0026.dbr
echo onDestroy,dail.summon.dailskillsummon0027, >> .\items\summon\dailskillsummon0027.dbr
echo onDestroy,dail.summon.dailskillsummon0028, >> .\items\summon\dailskillsummon0028.dbr
echo onDestroy,dail.summon.dailskillsummon0029, >> .\items\summon\dailskillsummon0029.dbr
echo onDestroy,dail.summon.dailskillsummon0030, >> .\items\summon\dailskillsummon0030.dbr
echo onDestroy,dail.summon.dailfactionsummon00001, >> .\items\summon\dailfactionsummon0001.dbr
echo onDestroy,dail.summon.dailfactionsummon00002, >> .\items\summon\dailfactionsummon0002.dbr
echo onDestroy,dail.summon.dailfactionsummon00003, >> .\items\summon\dailfactionsummon0003.dbr

rem item text
rem itemText,tagOMtransfer1Desc,
echo itemText,tagDailThentyZShopping0001, >> .\items\summon\dailskillsummon0001.dbr
echo itemText,tagDailThentyZShopping0002, >> .\items\summon\dailskillsummon0002.dbr
echo itemText,tagDailThentyZShopping0003, >> .\items\summon\dailskillsummon0003.dbr
echo itemText,tagDailThentyZShopping0004, >> .\items\summon\dailskillsummon0004.dbr
echo itemText,tagDailThentyZShopping0005, >> .\items\summon\dailskillsummon0005.dbr
echo itemText,tagDailThentyZShopping0006, >> .\items\summon\dailskillsummon0006.dbr
echo itemText,tagDailThentyZShopping0007, >> .\items\summon\dailskillsummon0007.dbr
echo itemText,tagDailThentyZShopping0008, >> .\items\summon\dailskillsummon0008.dbr
echo itemText,tagDailThentyZShopping0009, >> .\items\summon\dailskillsummon0009.dbr
echo itemText,tagDailThentyZShopping0010, >> .\items\summon\dailskillsummon0010.dbr
echo itemText,tagDailThentyZShopping0011, >> .\items\summon\dailskillsummon0011.dbr
echo itemText,tagDailThentyZShopping0012, >> .\items\summon\dailskillsummon0012.dbr
echo itemText,tagDailThentyZShopping0013, >> .\items\summon\dailskillsummon0013.dbr
echo itemText,tagDailThentyZShopping0014, >> .\items\summon\dailskillsummon0014.dbr
echo itemText,tagDailThentyZShopping0015, >> .\items\summon\dailskillsummon0015.dbr
echo itemText,tagDailThentyZShopping0016, >> .\items\summon\dailskillsummon0016.dbr
echo itemText,tagDailThentyZShopping0017, >> .\items\summon\dailskillsummon0017.dbr
echo itemText,tagDailThentyZShopping0018, >> .\items\summon\dailskillsummon0018.dbr
echo itemText,tagDailThentyZShopping0019, >> .\items\summon\dailskillsummon0019.dbr
echo itemText,tagDailThentyZShopping0020, >> .\items\summon\dailskillsummon0020.dbr
echo itemText,tagDailThentyZShopping0021, >> .\items\summon\dailskillsummon0021.dbr
echo itemText,tagDailThentyZShopping0022, >> .\items\summon\dailskillsummon0022.dbr
echo itemText,tagDailThentyZShopping0023, >> .\items\summon\dailskillsummon0023.dbr
echo itemText,tagDailThentyZShopping0024, >> .\items\summon\dailskillsummon0024.dbr
echo itemText,tagDailThentyZShopping0025, >> .\items\summon\dailskillsummon0025.dbr
echo itemText,tagDailThentyZShopping0026, >> .\items\summon\dailskillsummon0026.dbr
echo itemText,tagDailThentyZShopping0027, >> .\items\summon\dailskillsummon0027.dbr
echo itemText,tagDailThentyZShopping0028, >> .\items\summon\dailskillsummon0028.dbr
echo itemText,tagDailThentyZShopping0029, >> .\items\summon\dailskillsummon0029.dbr
echo itemText,tagDailThentyZShopping0030, >> .\items\summon\dailskillsummon0030.dbr
echo itemText,tagDailDavoodFactioner, >> .\items\summon\dailfactionsummon0001.dbr
echo itemText,tagDailHardyFactioner, >> .\items\summon\dailfactionsummon0002.dbr
echo itemText,tagDailKhalanosFactioner, >> .\items\summon\dailfactionsummon0003.dbr

