templateName,database/templates/skill_attackbuffradius.tpl,
Class,Skill_AttackBuffRadius,
FileDescription,Attack Buff Radius,
buffSkillName,records/skills/playerclassEngineer/groundpound1_buff.dbr,
pointBlank,1,
